[package]
name = "day11"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc_runner = { path = "../../../libs/aoc_runner/rust" }
aoc_utils = { path = "../../../libs/rust/aoc_utils" }

[[bin]]
name = "2025_day11"
path = "day11.rs"
