[package]
name = "day02"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc_runner = { path = "../../../libs/rust/aoc_runner" }
aoc_utils = { path = "../../../libs/rust/aoc_utils" }

[[bin]]
name = "2025_day02"
path = "day02.rs"
