[package]
name = "day03"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc_runner = { path = "../../../libs/aoc-runner/rust" }
aoc_utils = { path = "../../../libs/rust/aoc_utils" }

[[bin]]
name = "2025_day03"
path = "day03.rs"
