[package]
name = "day12"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc_runner = { path = "../../../libs/aoc_runner/rust" }
aoc_utils = { path = "../../../libs/aoc_utils/rust" }

[[bin]]
name = "2025_day12"
path = "day12.rs"
