[package]
name = "day10"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc_runner = { path = "../../../libs/aoc_runner/rust" }
aoc_utils = { path = "../../../libs/rust/aoc_utils" }

# TODO:  Setup CMake so that this is checked, it needs sudo apt-get install
# coinor-cbc coinor-libcbc-dev or pacman -S coin-or-cbc
good_lp = "1.14.2"
regex = "1.12.2"

[[bin]]
name = "2025_day10"
path = "day10.rs"
